name: Python Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

jobs:
  security:
    runs-on: ubuntu-latest
    permissions:
      security-events: write  # Для интеграции с GitHub Security

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Установка зависимостей (чтобы Trivy их просканировал)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # или ваш файл зависимостей

      # Сканирование кода Python и зависимостей
      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'
          ignore-unfixed: false
          exit-code: '0'  # Не падать, но записать результаты

      # Загрузка результатов в GitHub Security Tab
      - name: Upload results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
