name: Code Linting

on:
  push:
    branches: [ main, master ]

  pull_request:
    branches: [ '*' ]


jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]

    steps:
      - uses: actions/checkout@v4

      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install linters
        run: pip install black flake8 mypy

      - name: Run Black
        run: black --check . || echo "⚠️ Run 'black .' locally to fix formatting"

      - name: Run Flake8
        run: flake8 . || echo "⚠️ Flake8 обнаружил проблему, но продолжил работу..."

      - name: Run Mypy
        run: mypy . || echo "⚠️ Mypy fonud обнаружил проблемы, но продолжил работу"
        
