name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        env: ["dev", "prod"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov flake8 mypy
    
    - name: Run tests with pytest (ENV=${{ matrix.env }})
      env:
        ENV: ${{ matrix.env }}
      run: |
        pytest tests/ --cov=./ --cov-report=xml
        coverage xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      if: matrix.env == 'dev' && matrix.python-version == '3.9'
    
    - name: Lint with flake8
      run: |
        flake8 core/ utils/ --count --show-source --statistics
    
    - name: Type checking with mypy
      run: |
        mypy --install-types --non-interactive core/ utils/
